"use client";

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  TrendingUp, 
  ShieldCheck, 
  Wallet, 
  Users, 
  ArrowRight, 
  Info, 
  ArrowUpRight,
  Landmark,
  Briefcase,
  History,
  AlertCircle,
  HelpCircle,
  ArrowRightLeft,
  Calendar,
  CreditCard,
  Building2,
  Zap
} from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { useCurrency } from "@/context/CurrencyContext";

// Sub-components
import BondRisks from './BondRisks';
import BondResearch from './BondResearch';

const topBonds = [
  {
    issuer: "KRAZYBEE SERVICES LIMITED",
    coupon: "10.50%",
    maturity: "Dec 2027",
    rating: "CRISIL A",
    yield: "11.30%",
    price: 99616.07,
    type: "Secured - Regular"
  },
  {
    issuer: "MANBA FINANCE LIMITED",
    coupon: "10.95%",
    maturity: "Oct 2027",
    rating: "CARE BBB+",
    yield: "11.25%",
    price: 100648.00,
    type: "Secured - Regular"
  },
  {
    issuer: "INDEL MONEY LIMITED",
    coupon: "9.75%",
    maturity: "Oct 2027",
    rating: "IVR A-",
    yield: "11.25%",
    price: 983.30,
    type: "Secured - Regular"
  }
];

const BondsOverview = () => {
  const { currency } = useCurrency();

  const faqData = [
    {
      q: "What is a Bond?",
      a: "Bonds can be issued by companies, governments, or corporations and generally pay a fixed interest rate at regular intervals. By buying a bond, you are giving the issuer a loan, and they agree to pay you back the face value of the loan on a specific date usually called the 'Maturity date'."
    },
    {
      q: "What are the different types of bonds available in our market?",
      a: "The different types of bonds include Sovereign bonds, PSU bonds, SDL (State Development Loan) bonds, and Corporate bonds."
    },
    {
      q: "What is the primary and secondary bond market?",
      a: "The Primary market is where investors buy directly from the issuing company when it goes public or sells its bonds for the first time. The Secondary market is where previously issued bonds are traded among investors. In the secondary market, the sale proceeds go to the investor selling the bond, not to the company."
    },
    {
      q: "What is credit rating in a bond?",
      a: "A credit rating is a financial indicator that represents the creditworthiness and quality of the bond. Different scales (AAA to D) represent the level of safety and risk of default."
    },
    {
      q: "Call Option date",
      a: "The call date is the date on which a bond can be redeemed before maturity. If the issuer feels there is a benefit to refinancing (like lower market rates), they may redeem the bond at par or a small premium."
    },
    {
      q: "Coupon Rate",
      a: "The coupon rate is the annual interest payment paid by the issuer relative to the bond's face value. It represents the yield paid by the bond."
    },
    {
      q: "IP date (Interest Payment Date)",
      a: "This is the specific date on which the interest payment of the bond is disbursed to the investor."
    },
    {
      q: "Yield to Maturity (YTM)",
      a: "YTM is the total return anticipated on a bond if it is held until it matures, expressed as an annual rate."
    },
    {
      q: "Price",
      a: "This is the present discounted value of future cash streams generated by the bond. It is the price where two parties agree to purchase/sell the bond."
    },
    {
      q: "Liquidity",
      a: "Bonds can be liquidated through the secondary market by identifying a potential buyer. Buying and selling ease depends on bond quality and prevailing interest rates. Brokers may help find buyers, but it is not mandatory for them to do so."
    },
    {
      q: "Mode of Purchase",
      a: "Bonds must be compulsorily purchased through a Demat account. Investors are expected to hold a Demat account to store and trade bonds."
    }
  ];

  return (
    <div className="space-y-12 animate-in fade-in duration-500 pb-12">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-700 to-blue-900 text-white rounded-[2.5rem] p-8 md:p-12 shadow-xl relative overflow-hidden">
        <div className="relative z-10 space-y-6">
          <div className="flex flex-wrap gap-3">
             <Badge className="bg-blue-500/30 text-blue-100 hover:bg-blue-500/40 border-none px-3 py-1">
               Fixed Income
             </Badge>
             <Badge className="bg-emerald-500/30 text-emerald-100 hover:bg-emerald-500/40 border-none px-3 py-1">
               Rated & Listed
             </Badge>
          </div>
          <h2 className="text-3xl md:text-5xl font-bold leading-tight max-w-2xl">
            Lend to Giants & Earn Up to 12%*
          </h2>
          <p className="text-blue-100 text-lg max-w-xl">
            By buying a bond, you give a loan to an issuer (Govt or Company) who pays you back with fixed interest.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 pt-4">
            <Button size="lg" className="bg-white text-blue-900 hover:bg-blue-50 font-bold px-8">
              Explore Bond Market
            </Button>
          </div>
        </div>
        <div className="absolute bottom-10 right-10 opacity-20 hidden md:block">
          <Landmark size={240} strokeWidth={0.5} />
        </div>
      </section>

      {/* Bond Types Grid */}
      <section className="space-y-6">
        <h3 className="text-2xl font-bold">Types of Bonds</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Sovereign Bonds", icon: <ShieldCheck className="text-emerald-500" /> },
            { label: "PSU Bonds", icon: <Building2 className="text-blue-500" /> },
            { label: "SDL Bonds", icon: <Landmark className="text-indigo-500" /> },
            { label: "Corporate Bonds", icon: <Briefcase className="text-orange-500" /> }
          ].map((type, i) => (
            <div key={i} className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-slate-50 flex items-center justify-center mx-auto">
                {type.icon}
              </div>
              <p className="text-sm font-bold text-slate-900">{type.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Primary vs Secondary */}
      <section className="grid md:grid-cols-2 gap-8">
        <Card className="border-slate-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Zap className="w-5 h-5 text-amber-500" /> Primary Market
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-slate-600 leading-relaxed">
            Where investors buy directly from the issuing company as it goes public or sells its bonds for the first time.
          </CardContent>
        </Card>
        <Card className="border-slate-200">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ArrowRightLeft className="w-5 h-5 text-blue-500" /> Secondary Market
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-slate-600 leading-relaxed">
            Where previously issued bonds are traded among investors. Sale proceeds go to the investor, not the company.
          </CardContent>
        </Card>
      </section>

      <BondRisks />
      <BondResearch />

      {/* Bond Examples */}
      <section className="space-y-8">
        <h3 className="text-2xl font-bold">Bond Selection Examples</h3>
        <div className="grid lg:grid-cols-3 gap-6">
          {topBonds.map((bond, i) => (
            <Card key={i} className="overflow-hidden hover:shadow-lg transition-all border-slate-200">
              <CardHeader className="bg-slate-50/50 border-b pb-4">
                <div className="flex justify-between items-start mb-2">
                  <Badge variant="outline" className="bg-white border-slate-300 text-[10px]">{bond.rating}</Badge>
                  <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full"><ArrowUpRight className="w-4 h-4" /></Button>
                </div>
                <CardTitle className="text-md leading-tight">{bond.issuer}</CardTitle>
                <CardDescription className="text-xs">{bond.type}</CardDescription>
              </CardHeader>
              <CardContent className="pt-6 space-y-6">
                <div className="grid grid-cols-2 gap-4 text-xs">
                  <div><p className="text-slate-400 uppercase font-bold">Coupon</p><p className="font-bold text-slate-900">{bond.coupon}</p></div>
                  <div><p className="text-slate-400 uppercase font-bold">Maturity</p><p className="font-bold text-slate-900">{bond.maturity}</p></div>
                  <div><p className="text-slate-400 uppercase font-bold">Yield (YTM)</p><p className="font-bold text-emerald-600">{bond.yield}</p></div>
                  <div><p className="text-slate-400 uppercase font-bold">Price</p><p className="font-bold text-slate-900">{currency.symbol}{bond.price.toLocaleString()}</p></div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Full FAQ Section */}
      <section className="max-w-4xl mx-auto space-y-8">
        <h3 className="text-3xl font-bold text-center flex items-center justify-center gap-3"><HelpCircle className="w-8 h-8 text-primary" /> Bonds - FAQ</h3>
        <Accordion type="single" collapsible className="w-full">
          {faqData.map((item, i) => (
            <AccordionItem key={i} value={`item-${i}`}>
              <AccordionTrigger className="text-left">{item.q}</AccordionTrigger>
              <AccordionContent className="text-slate-600 leading-relaxed">
                {item.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* Mode of Purchase reminder */}
      <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6 flex flex-col md:flex-row gap-6 items-center">
        <div className="p-4 bg-white rounded-xl shadow-sm">
          <CreditCard className="w-8 h-8 text-blue-600" />
        </div>
        <div className="space-y-1">
          <h4 className="text-lg font-bold text-blue-900">Mode of Purchase</h4>
          <p className="text-sm text-blue-800 leading-relaxed">
            Bonds must be compulsorily purchased through a <strong>Demat account</strong>. Ensure your Demat is active before bidding in the primary or secondary market.
          </p>
        </div>
      </div>
    </div>
  );
};

export default BondsOverview;